#UAT Properties

#spring.datasource.url=jdbc:postgresql://10.247.141.198:5432/prashast
#spring.datasource.username=pgi_test
#spring.datasource.password=postgresdemo


spring.datasource.url=jdbc:postgresql://10.247.141.198:5432/prashast
spring.datasource.username=prashastapp
spring.datasource.password=prashasT$demo34

#spring.datasource.username=prashastapp
#spring.datasource.password=prashasT$demo34

#spring.datasource.password=root
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs
#udise.base.api.url = https://api.udiseplus.gov.in
udise.base.api.url = https://demo.udiseplus.gov.in

#certificate.path = /opt/udiseplustestingapis.cer
#certificate.path = D:\\MOE-Prashast\\udiseplustestingapis.cer
#certificate.path = "D:\\Sharique\\NIC_Doc\\prashast_DOC\\udiseplustestingapis.cer"
certificate.path = D:\\certificat\\udiseplustestingapis.cer
clientId=ncert-prashast-testing
clientSecret=test@123


#proxy.host=10.194.150.152
#proxy.port=3128

logging.level.root=DEBUG
logging.level.reactor.netty=DEBUG
logging.level.org.springframework.web.reactive.function.client=DEBUG

# Redis  config
spring.data.redis.host=10.247.141.198
spring.data.redis.port=6379
spring.data.redis.timeout=2000
spring.data.redis.password=Redis@prashast2025

app.login.session.db.enabled=true

access.token.expiry.time=86400
refresh.token.expiry.time=604800

